### ISSUE TITLE
How to use Jmeter for UI performance testing?

### ISSUE THREAD

**Issue by mhdmaktabi** [aliesbelik/awesome-jmeter#13]
Hi,

I would like to use Jmeter for UI performance testing.
How to use Jmeter for UI performance testing?
How can I get the loading time of the HTML elements?

Thanks

**Comment by Kitichka** [comment]
Use 'jp@gc - Chrome Driver Config’ element


where chromedriver.exe is a driver for browser.

For performance test use 'jp@gc - Webdriver Sampler’ 


Code looks crappy, but as example it’s fine

Kind regards, 
Eugene

**Comment by mhdmaktabi** [comment]
I don't really see the point of doing this in Jmeter. You won't be able to create much load if every single Jmeter user needs to create and control a whole Browser instance (each one using a significant amount of memory and CPU).

**Comment by Kitichka** [comment]
I know only one case when example above can be used: When require to measure time of page load in browser (i.e measure time when elements on the page will be visible when user open page or do any actions via browser).
For the other cases, this solution does not fit!

**Comment by mhdmaktabi** [comment]
Any example of measuring the time of page-load in browser?

**Comment by Kitichka** [comment]
'Aggregate Report' listener can help to measure time. The case looks as follows: User need to enter login and pass and click submit button to login to app via browser
We add 2 samplers: 1st sampler will open required URL and fill login and password fields. The 2nd will do click on submit button and wait the longest load element on the next page, where user redirected once login to app. With 'Aggregate Report' listener we will analyze load time of the 2nd sampler. 
With this case we exclude time for preparation cases (when user fill fields) and measure only the useful time (time between submit button click and when expected element will be displayed on the next page). 
Something like that

**Comment by aliesbelik** [comment]
Hi @mhdmaktabi.
For asking such specific questions, not directly related to this repo content, using any load-testing or JMeter-related Q&A community or user-group seems to be better idea.
Thank you.

**Comment by mhdmaktabi** [comment]
Hi @Kitichka 

I need to simulate 500 users. but in your way, I couldn't run more than 25 headless chrome instances.
Any idea?

**Comment by Kitichka** [comment]
Use remote servers for that. More details available here: https://jmeter.apache.org/usermanual/remote-test.html
